from dotenv import load_dotenv
from providers.gemini_provider import chat_with_gemini
from providers.groq_provider import chat_with_groq
from providers.openrouter_provider import chat_with_openrouter
from utils.json_utils import display_response
from utils.system_utils import create_system_message
from utils.command_utils import handle_command
from utils.json_mode_utils import check_json_mode
from utils.provider_utils import choose_provider

load_dotenv(override=True)

system_message = create_system_message()

messages = [system_message]

provider = choose_provider()

print("Using:", provider)

while True:

    user_input = input("You: ")

    json_mode, user_input = check_json_mode(user_input)

    should_quit, new_messages = handle_command(
        user_input,
        system_message
    )

    if should_quit:
        break

    if new_messages:
        messages = new_messages
        continue

    if json_mode:
        messages.append(    #here chats will get append at last one by one
            {
                "role": "user",  #role -> each role-persons may chnge.
                "content":
                f"""
    Return ONLY valid JSON.

    Use this format:
    {{
        "topic" : "...",
        "summary" : "..."
    }}

    Question:
    {user_input}
    """
            }
        )

    else:
        messages.append(
            {
                "role": "user",
                "content": user_input
            }
        )

    print(messages)

    if provider == "groq":
        bot_reply, input_tokens, output_tokens = (
            chat_with_groq(messages)
        )

    elif provider == "gemini":
        bot_reply, input_tokens, output_tokens = (
            chat_with_gemini(messages)
        )

    elif provider == "openrouter":
        bot_reply,input_tokens,output_tokens = (
            chat_with_openrouter(messages)
        )

    display_response(bot_reply, json_mode)

    messages.append(
        {
            "role": "assistant",
            "content": bot_reply
            #extracts the actual text generated by the model.
        }
    )

    print("\nToken Usage:")
    print("Input Tokens:", input_tokens)
    print("Output Tokens:", output_tokens)


#response:- Ye pura object hai jo API se aata hai jab tum client.chat.completions.create(...) call karte ho.
#Ye answers ek list (choices) mei hote hain