from dotenv import load_dotenv
from groq import Groq
import os

load_dotenv(override=True)

groq_api_key = os.getenv("GROQ_API_KEY")

client = Groq(api_key=groq_api_key)

system_message = {
    "role": "system",
    "content": "You are a helpful assistant."
}

messages = [system_message]

while True:
    user_input = input("You: ")

    if user_input == "/quit":
        print("Goodbye!")
        break

    if user_input == "/clear":
        messages = [system_message]
        print("Conversation history cleared!")
        continue

    messages.append(    #here chats will get append at last one by one
        {
            "role": "user",  #role -> each role-persons may chnge.
            "content": user_input
        }
    )

    print(messages)

    response = client.chat.completions.create(  #A brand new API request is sent every time the user enters a message.
        model="llama-3.1-8b-instant",
        messages=messages
    )


    print("Bot:", response.choices[0].message.content)
    messages.append(
        {
            "role": "assistant",
            "content": response.choices[0].message.content #extracts the actual text generated by the model.
        }
    )
    print("\nToken Usage:")
    print("Input Tokens:", response.usage.prompt_tokens)
    print("Output Tokens:", response.usage.completion_tokens)












#response:- Ye pura object hai jo API se aata hai jab tum client.chat.completions.create(...) call karte ho.
#Ye answers ek list (choices) mei hote hain